### ISSUE TITLE
单品分类功能

### ISSUE THREAD

**Issue by pannanxu** [pannanxu/halo-plugin-mall#3]
需求：实现单品分类的 dialect 指令能够在主题中使用

Extension 结构如下

```yaml
apiVersion: v1alpha1
kind: "MallCategory"
metadata:
  name: mall-categories
spec:
  displayName: "name"
  slug: "slug"
  description: "description"
  cover: "cover"
  template: "template"
  priority: ""
  children: ""
status:
  permalink: "permalink"
  count: 1
  visiblePostCount: 1
```
